apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskboard-backend
  namespace: taskboard
  labels:
    app: taskboard-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskboard-backend
  template:
    metadata:
      labels:
        app: taskboard-backend
    spec:
      containers:
        - name: backend
          image: r44gh4v/taskboard-backend:__IMAGE_TAG__
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "sqlite:///./taskboard.db"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskboard-frontend
  namespace: taskboard
  labels:
    app: taskboard-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskboard-frontend
  template:
    metadata:
      labels:
        app: taskboard-frontend
    spec:
      containers:
        - name: frontend
          image: r44gh4v/taskboard-frontend:__IMAGE_TAG__
          ports:
            - containerPort: 80
